APP_NAME=ENV["APP_NAME"]
BUILD_NUMBER=1
BUILD_VERSION="1.0.0"
FIREBASE_APP_ID=ENV["FIREBASE_APP_ID"]
FIREBASE_TESTER_GROUP=ENV["FIREBASE_TESTER_GROUP"]

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :deploy_android do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
      app: FIREBASE_APP_ID,
      groups: FIREBASE_TESTERS_GROUP,
      release_notes_file: "Bug fixes. Updates."
    )
    telegram(
      token: ENV['TG_BOT_TOKEN'], # get token from @BotFather
      chat_id: ENV['TG_CHAT_ID'], # https://stackoverflow.com/questions/33858927/how-to-obtain-the-chat-id-of-a-private-telegram-channel
      text: "TELEGRAM_ANDROID_TEXT", # Required
    )
  end
end
